ALTER TABLE recipes ADD COLUMN region TEXT DEFAULT '';
ALTER TABLE recipes ADD COLUMN is_system INTEGER DEFAULT 0;
ALTER TABLE ingredients ADD COLUMN is_system INTEGER DEFAULT 0;
ALTER TABLE ingredients ADD COLUMN alt_unit TEXT DEFAULT '';
ALTER TABLE ingredients ADD COLUMN alt_quantity REAL DEFAULT 0;
