ALTER TABLE ingredients ADD COLUMN iron REAL DEFAULT 0;
ALTER TABLE ingredients ADD COLUMN calcium REAL DEFAULT 0;
ALTER TABLE ingredients ADD COLUMN vitamin_c REAL DEFAULT 0;
ALTER TABLE ingredients ADD COLUMN vitamin_a REAL DEFAULT 0;
ALTER TABLE ingredients ADD COLUMN sodium REAL DEFAULT 0;
ALTER TABLE ingredients ADD COLUMN potassium REAL DEFAULT 0;

ALTER TABLE nutrition_log ADD COLUMN person_id INTEGER REFERENCES persons(id) ON DELETE SET NULL;
ALTER TABLE nutrition_log ADD COLUMN iron REAL DEFAULT 0;
ALTER TABLE nutrition_log ADD COLUMN calcium REAL DEFAULT 0;
